name: {{project_name.snakeCase()}}
description: {{project_name}} is a new Flutter project created with the Mason CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^16.2.0
  google_fonts: ^6.3.0
  injectable: ^2.5.1
  intl: ^0.20.2
  retrofit: ^4.7.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.3.0
  injectable_generator: ^2.8.1
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.2
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
