name: {{app_name.snakeCase()}}
description: {{app_description}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fresh_dio: ^0.4.3
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  hydrated_bloc: ^10.1.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  pinput: ^5.0.2
  pull_to_refresh: ^2.0.0
  retrofit: ^4.7.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.3.1
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.6
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
